name: login
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  provider: ^6.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.2.6
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/AQ.png
    - assets/images/17.jpeg
    - assets/images/IMG_9421.jpg
    - assets/images/1182728b0d17d4a20f5c7c4e22709b30.jpg
    - assets/images/taxxx.jpg
    - assets/images/3.jpg
    - assets/images/13.webp
    - assets/images/14.jpg
    - assets/images/20.jpg
    - assets/images/fish.jpg
    - assets/images/many.jpg
    - assets/images/black.png
    - assets/images/paypal.png
